def generate_readme(data: dict) -> str:
    sections = []

    sections.append(render_title(data))
    sections.append(render_description(data))
    sections.append(render_languages(data))
    sections.append(render_dependencies(data))
    sections.append(render_file_structure(data))
    sections.append(render_docker(data))

    return "\n\n".join(section for section in sections if section)


def render_title(data: dict) -> str:
    return f"# {data['project_name']}"


def render_description(data: dict) -> str:
    languages = ", ".join(data.get("languages", []))
    return (
        "## Project Overview\n\n"
        f"This project is built using {languages}. "
        "This README was automatically generated by analyzing the repository "
        "structure and configuration files."
    )


def render_languages(data: dict) -> str:
    lines = ["## Languages & Frameworks", ""]
    for lang in data.get("languages", []):
        lines.append(f"- {lang}")
    return "\n".join(lines)


def render_dependencies(data: dict) -> str:
    deps = data.get("dependencies", {})
    lines = ["## Dependencies", ""]

    if "python" in deps and deps["python"]:
        lines.append("### Python")
        for dep in deps["python"]:
            lines.append(f"- {dep}")

    if "node" in deps and deps["node"]:
        lines.append("\n### Node.js")
        for dep in deps["node"]:
            lines.append(f"- {dep}")

    return "\n".join(lines)


def render_file_structure(data: dict) -> str:
    lines = [
        "## File Structure",
        "",
        "```text",
    ]

    for path in data.get("file_tree", []):
        lines.append(path)

    lines.append("```")
    return "\n".join(lines)


def render_docker(data: dict) -> str:
    docker = data.get("docker", {})

    if not docker or not any(docker.values()):
        return ""

    lines = ["## Docker Support", ""]

    if docker.get("dockerfile"):
        lines.append("- Dockerfile detected")

    if docker.get("docker_compose"):
        lines.append("- docker-compose.yml detected")

    return "\n".join(lines)
